name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Upload build folder
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_WATER_0B405211E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "build"           # NOTE: This points to the prebuilt build folder
          output_location: ""             # Leave blank because no build is happening
